Repository caoyingjunz/csi-driver-localstorage, pull requests merged in 2021-06, with the labels that each got.

#25 Improved images building.
  Dockerfile
  Makefile
  README.md
Labels: documentation, enhancement

#24 Add Admission controller
  cmd/pixiu-webhook-server/pixiu-webhook-server.go
  config/webhook/deploy.sh
  config/webhook/generate-keys.sh
  config/webhook/pixiu-namespace.yaml
  config/webhook/pixiu-webhook-server.yaml
  config/webhook/test/admission-pod-on-all.yaml
  config/webhook/test/admission-pod-on-mutate.yaml
  config/webhook/test/admission-pod-on-validate.yaml
  config/webhook/test/admission-pod-test.yaml
  pkg/controller/webhook/webhook_controller.go
  pkg/controller/webhook/webhook_controller_test.go
Labels: enhancement

#38 Fix webhook install failed
  config/webhook/deploy.sh
Labels: bug

#49 Fix GetAvailableResource Func, For Is Not Continue
  cmd/pixiu-controller-manager/app/controllermanager.go
Labels: bug
